// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnfidswwfhyoulltsvax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZuZmlkc3d3Zmh5b3VsbHRzdmF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NDUwMTgsImV4cCI6MjA3MzUyMTAxOH0.asHERfWd8VnSeidOhJEzMpZgB3ZX4Vsx2Vdmul2s_qM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});